version: '3.8'

services:
  postgres:
    image: postgres
    user: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"

  api-service:
      build: ./Backend/
      volumes: 
          - ./Backend/:/usr/src/app/
      ports: 
          - 5000:5000
      environment: 
          PORT: 5000
          FLASK_DEBUG: 1
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_PORT: ${POSTGRES_PORT}